// pages/index.vue
<template>
  <v-row justify="center" align="center">
    <v-col cols="12" sm="8" md="6">
      <v-card>
        <v-card-title class="headline">
          Welcome to the Vuetify + Nuxt.js template
        </v-card-title>
        <v-card-text> Pocketのリストをもっとみやすくする </v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn color="primary" rounded @click="login">
            Login with Pocket
          </v-btn>
        </v-card-actions>
      </v-card>
    </v-col>
  </v-row>
</template>

<script>
import { Component, Vue } from 'nuxt-property-decorator'
import client from '../assets/client'

@Component
export default class IndexPage extends Vue {
  mounted() {
    if (client.loggedIn()) {
      this.$router.push('/authed/list')
    }
  }

  async login() {
    const { loggedIn, transition } = await client.tryLogin()
    if (loggedIn) {
      alert('already logined')
      this.$router.push('/authed/list')
      return
    } else if (transition) {
      window.location.href = transition
      return
    }
    alert('failed to try login')
  }
}
</script>

// pages/index.tsx
import Head from 'next/head'
import router from 'next/router'
import styles from '../styles/Home.module.css'
import client from '../assets/client'

async function login() {
  const { loggedIn, transition } = await client.tryLogin()
  if (loggedIn) {
    alert('already logined')
    router.push('/authed/list')
    return
  } else if (transition) {
    router.push(transition)
    return
  }
  alert('failed to try login')
}

export default function Home() {
  if (client.loggedIn()) {
    router.push('/authed/list')
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>pocket-list</title>
        <meta name="description" content="websites' list on getpocket" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          pocket-list
        </h1>

        <button onClick={login}>login with pocket</button>
      </main>
    </div>
  )
}
