// pages/redirected.vue
<template>
  <div></div>
</template>

<script lang="ts">
import { Component, Vue } from 'nuxt-property-decorator'
import client from '../assets/client'

@Component
export default class RedirectedPage extends Vue {
  async mounted() {
    if (await client.login()) {
      this.$router.push('/authed/list')
    } else {
      this.$router.push('/')
    }
  }
}
</script>

// pages/redirected.tsx
import router from 'next/router'
import client from '../assets/client'
export default function Redirected() {
  if (process.browser) {
    client.login().then(loggedIn => {
      if (loggedIn)  {
      router.push('/authed/list')
      } else {
      router.push('/')
      }
    })
  }
  return (
    <div>
      a
    </div>
  )
}
